/* eslint-disable */
// Generated by scripts/export_openapi.py. Do not edit by hand.

export type ActivateWorkflowRolloutRequest = {
  "candidate_version_id": string;
};

export type ApprovalDecisionRequest = {
  "status": ApprovalStatus;
  "decision_note"?: string | null;
};

export type ApprovalRequestRead = {
  "id": string;
  "project_id": string;
  "run_id": string;
  "tool_call_id": string;
  "approver_role": MembershipRole;
  "status": ApprovalStatus;
  "reason": string;
  "run_context"?: Record<string, unknown> | null;
  "proposed_effect"?: Record<string, unknown> | null;
  "requested_at": string;
  "decided_at"?: string | null;
  "decided_by"?: string | null;
  "decision_note"?: string | null;
};

export type ApprovalStatus = "pending" | "approved" | "rejected" | "cancelled";

export type AuditEventRead = {
  "id": string;
  "actor_user_id"?: string | null;
  "org_id"?: string | null;
  "project_id"?: string | null;
  "action": string;
  "resource_type": string;
  "resource_id"?: string | null;
  "before"?: Record<string, unknown> | null;
  "after"?: Record<string, unknown> | null;
  "created_at": string;
};

export type AuthSessionRead = {
  "user_id": string;
  "memberships": MembershipRead[];
};

export type ConnectorAuthMode = "none" | "api_key" | "oauth" | "service_account";

export type ConnectorCreate = {
  "name": string;
  "connector_type"?: ConnectorType;
  "auth_mode"?: ConnectorAuthMode;
  "scopes"?: string[];
  "status"?: ConnectorStatus;
};

export type ConnectorRead = {
  "id": string;
  "org_id"?: string | null;
  "project_id"?: string | null;
  "name": string;
  "connector_type": ConnectorType;
  "auth_mode": ConnectorAuthMode;
  "scopes": string[];
  "status": ConnectorStatus;
  "owner_user_id"?: string | null;
  "created_at": string;
};

export type ConnectorStatus = "active" | "degraded" | "disabled" | "unknown";

export type ConnectorType = "mcp" | "local";

export type DatasetCreate = {
  "name": string;
  "version": string;
  "description"?: string | null;
};

export type DatasetRead = {
  "id": string;
  "project_id": string;
  "name": string;
  "version": string;
  "description"?: string | null;
  "created_by"?: string | null;
  "created_at": string;
};

export type EvalCaseCreate = {
  "input_payload": Record<string, unknown>;
  "expected"?: Record<string, unknown>;
  "tags"?: string[];
};

export type EvalCaseRead = {
  "id": string;
  "dataset_id": string;
  "input_payload": Record<string, unknown>;
  "expected": Record<string, unknown>;
  "tags": string[];
  "created_at": string;
};

export type EvalCaseResultRead = {
  "id": string;
  "eval_run_id": string;
  "eval_case_id": string;
  "run_id"?: string | null;
  "status": EvalCaseStatus;
  "scores": Record<string, unknown>;
  "output"?: Record<string, unknown> | null;
  "trace_grade"?: Record<string, unknown> | null;
  "error"?: Record<string, unknown> | null;
  "created_at": string;
};

export type EvalCaseStatus = "pending" | "succeeded" | "failed";

export type EvalRunCreate = {
  "dataset_id": string;
  "workflow_version_id": string;
  "baseline_version_id"?: string | null;
};

export type EvalRunRead = {
  "id": string;
  "dataset_id": string;
  "workflow_version_id": string;
  "baseline_version_id"?: string | null;
  "status": EvalRunStatus;
  "summary": Record<string, unknown>;
  "started_at"?: string | null;
  "ended_at"?: string | null;
  "created_at": string;
};

export type EvalRunStatus = "queued" | "running" | "succeeded" | "failed";

export type HTTPValidationError = {
  "detail"?: ValidationError[];
};

export type MembershipCreate = {
  "user_id": string;
  "role": MembershipRole;
};

export type MembershipRead = {
  "id": string;
  "user_id": string;
  "org_id": string;
  "project_id"?: string | null;
  "role": MembershipRole;
  "created_at": string;
};

export type MembershipRole = "platform_admin" | "org_admin" | "project_admin" | "ai_engineer" | "supervisor" | "team_lead" | "operator" | "analyst" | "api_client";

export type ModelConfig = {
  "provider": string;
  "name": string;
  "temperature"?: number;
  "max_output_tokens"?: number | null;
};

export type OrganizationCreate = {
  "name": string;
  "slug": string;
};

export type OrganizationRead = {
  "id": string;
  "name": string;
  "slug": string;
  "created_at": string;
};

export type PolicyAction = "allow" | "deny" | "require_approval";

export type ProjectCreate = {
  "name": string;
  "slug": string;
  "environment"?: ProjectEnvironment;
};

export type ProjectEnvironment = "dev" | "staging" | "prod";

export type ProjectRead = {
  "id": string;
  "org_id": string;
  "name": string;
  "slug": string;
  "environment": ProjectEnvironment;
  "created_at": string;
};

export type PublishWorkflowVersionRequest = {
  "published_by"?: string | null;
};

export type RollbackThresholds = {
  "policy_violation_rate"?: number | null;
  "schema_failure_rate"?: number | null;
  "p95_latency_ms"?: number | null;
};

export type RolloutMonitorRead = {
  "workflow_id": string;
  "active_version_id"?: string | null;
  "baseline_version_id"?: string | null;
  "candidate_version_id"?: string | null;
  "decision": string;
  "thresholds_breached"?: string[];
  "candidate_runs"?: number;
  "baseline_runs"?: number;
  "candidate_failure_rate"?: number | null;
  "baseline_failure_rate"?: number | null;
  "candidate_p95_latency_ms"?: number | null;
  "baseline_p95_latency_ms"?: number | null;
};

export type RolloutStrategy = "direct" | "canary" | "shadow" | "ab_compare";

export type RolloutTrafficSplit = {
  "baseline": number;
  "candidate": number;
};

export type RunRead = {
  "id": string;
  "project_id": string;
  "workflow_version_id": string;
  "triggered_by"?: string | null;
  "status": RunStatus;
  "input_payload": Record<string, unknown>;
  "final_output"?: Record<string, unknown> | null;
  "started_at"?: string | null;
  "ended_at"?: string | null;
  "latency_ms"?: number | null;
  "cost_usd"?: string | null;
  "tokens_input"?: number | null;
  "tokens_output"?: number | null;
  "feedback_score"?: string | null;
  "created_at": string;
};

export type RunStatus = "queued" | "running" | "awaiting_approval" | "resumed" | "succeeded" | "failed" | "cancelled";

export type RunSubmitRequest = {
  "workflow_version_id": string;
  "input_payload": Record<string, unknown>;
  "triggered_by"?: string | null;
};

export type RunTimelineRead = {
  "run": RunRead;
  "trace_spans": TraceSpanRead[];
  "tool_calls": ToolCallRead[];
  "approvals": ApprovalRequestRead[];
};

export type RunTransitionRequest = {
  "status": RunStatus;
  "final_output"?: Record<string, unknown> | null;
  "latency_ms"?: number | null;
  "cost_usd"?: number | string | null;
  "tokens_input"?: number | null;
  "tokens_output"?: number | null;
};

export type SetActiveWorkflowVersionRequest = {
  "workflow_version_id": string;
};

export type SpanStatus = "ok" | "error" | "cancelled" | "in_progress";

export type ToolCallRead = {
  "id": string;
  "project_id": string;
  "run_id": string;
  "span_id"?: string | null;
  "tool_name": string;
  "args": Record<string, unknown>;
  "status": ToolCallStatus;
  "approval_required": boolean;
  "approval_id"?: string | null;
  "result"?: Record<string, unknown> | null;
  "error"?: Record<string, unknown> | null;
  "idempotency_key"?: string | null;
  "created_at": string;
};

export type ToolCallStatus = "proposed" | "blocked" | "approved" | "executed" | "rejected" | "failed";

export type ToolDefinitionCreate = {
  "name": string;
  "description": string;
  "risk_level": ToolRiskLevel;
  "input_schema"?: Record<string, unknown>;
  "output_schema"?: Record<string, unknown>;
  "is_mutating"?: boolean;
};

export type ToolDefinitionRead = {
  "id": string;
  "connector_id": string;
  "name": string;
  "description": string;
  "risk_level": ToolRiskLevel;
  "input_schema": Record<string, unknown>;
  "output_schema": Record<string, unknown>;
  "is_mutating": boolean;
  "created_at": string;
};

export type ToolRiskLevel = "low" | "medium" | "high";

export type TraceSpanCreate = {
  "trace_id": string;
  "span_id": string;
  "parent_span_id"?: string | null;
  "span_type": string;
  "name": string;
  "status": SpanStatus;
  "started_at"?: string | null;
  "ended_at"?: string | null;
  "attributes"?: Record<string, unknown>;
  "error"?: Record<string, unknown> | null;
};

export type TraceSpanRead = {
  "id": string;
  "project_id": string;
  "workflow_version_id"?: string | null;
  "run_id": string;
  "trace_id": string;
  "span_id": string;
  "parent_span_id"?: string | null;
  "span_type": string;
  "name": string;
  "status": SpanStatus;
  "started_at": string;
  "ended_at"?: string | null;
  "attributes": Record<string, unknown>;
  "error"?: Record<string, unknown> | null;
  "created_at": string;
};

export type ValidationError = {
  "loc": string | number[];
  "msg": string;
  "type": string;
  "input"?: unknown;
  "ctx"?: Record<string, unknown>;
};

export type WorkflowCreate = {
  "slug": string;
  "name": string;
  "domain": string;
  "description"?: string | null;
};

export type WorkflowPolicyRule = {
  "name": string;
  "when": string;
  "action": PolicyAction;
  "approver_role"?: MembershipRole | null;
};

export type WorkflowRead = {
  "id": string;
  "project_id": string;
  "active_version_id"?: string | null;
  "slug": string;
  "name": string;
  "domain": string;
  "description"?: string | null;
  "created_at": string;
};

export type WorkflowRolloutConfig = {
  "strategy"?: RolloutStrategy;
  "baseline_version"?: string | null;
  "candidate_version"?: string | null;
  "traffic_split"?: RolloutTrafficSplit | null;
  "rollback_thresholds"?: RollbackThresholds | null;
};

export type WorkflowRunSubmitRequest = {
  "input_payload": Record<string, unknown>;
  "triggered_by"?: string | null;
};

export type WorkflowToolRef = {
  "name": string;
  "connector_id"?: string | null;
};

export type WorkflowVersionCreate = {
  "version": string;
  "prompt_template": string;
  "input_schema": Record<string, unknown>;
  "output_schema": Record<string, unknown>;
  "model_config": ModelConfig;
  "policy_pack"?: WorkflowPolicyRule[];
  "tool_set"?: WorkflowToolRef[];
  "guardrails"?: string[];
  "rollout_config"?: WorkflowRolloutConfig | null;
  "eval_dataset_bindings"?: string[];
  "created_by"?: string | null;
};

export type WorkflowVersionRead = {
  "id": string;
  "workflow_id": string;
  "version": string;
  "status": WorkflowVersionStatus;
  "prompt_template": string;
  "input_schema": Record<string, unknown>;
  "output_schema": Record<string, unknown>;
  "model_config": ModelConfig;
  "policy_pack": WorkflowPolicyRule[];
  "tool_set": WorkflowToolRef[];
  "guardrails": string[];
  "rollout_config"?: WorkflowRolloutConfig | null;
  "eval_dataset_bindings": string[];
  "created_by"?: string | null;
  "created_at": string;
  "published_at"?: string | null;
};

export type WorkflowVersionStatus = "draft" | "published" | "archived";

export type WorkflowVersionUpdate = {
  "version"?: string | null;
  "prompt_template"?: string | null;
  "input_schema"?: Record<string, unknown> | null;
  "output_schema"?: Record<string, unknown> | null;
  "model_config"?: ModelConfig | null;
  "policy_pack"?: WorkflowPolicyRule[] | null;
  "tool_set"?: WorkflowToolRef[] | null;
  "guardrails"?: string[] | null;
  "rollout_config"?: WorkflowRolloutConfig | null;
  "eval_dataset_bindings"?: string[] | null;
};
