from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from arp_api.main import create_app


ROOT = Path(__file__).resolve().parents[1]
OPENAPI_PATH = ROOT / "apps" / "api" / "openapi" / "openapi.json"
TYPES_PATH = ROOT / "apps" / "web" / "src" / "lib" / "api" / "types.ts"


def _type_name(name: str) -> str:
    parts = [part for part in re.split(r"[^0-9A-Za-z]+", name) if part]
    normalized = "".join(part[:1].upper() + part[1:] for part in parts) or "Schema"
    if normalized[0].isdigit():
        return f"Schema{normalized}"
    return normalized


def _schema_to_ts(schema: dict[str, Any], schemas: dict[str, Any]) -> str:
    if "$ref" in schema:
        return _type_name(schema["$ref"].rsplit("/", 1)[-1])
    if "anyOf" in schema:
        return " | ".join(_schema_to_ts(item, schemas) for item in schema["anyOf"])
    if "enum" in schema:
        return " | ".join(json.dumps(item) for item in schema["enum"])

    schema_type = schema.get("type")
    if schema_type == "array":
        return f"{_schema_to_ts(schema.get('items', {}), schemas)}[]"
    if schema_type == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        if not properties:
            additional = schema.get("additionalProperties")
            if isinstance(additional, dict):
                return f"Record<string, {_schema_to_ts(additional, schemas)}>"
            return "Record<string, unknown>"
        lines = ["{"]
        for key, value in properties.items():
            optional = "" if key in required else "?"
            lines.append(f"  {json.dumps(key)}{optional}: {_schema_to_ts(value, schemas)};")
        lines.append("}")
        return "\n".join(lines)
    if schema_type == "integer" or schema_type == "number":
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "string":
        return "string"
    if schema_type == "null":
        return "null"
    return "unknown"


def _render_types(openapi: dict[str, Any]) -> str:
    schemas = openapi.get("components", {}).get("schemas", {})
    lines = [
        "/* eslint-disable */",
        "// Generated by scripts/export_openapi.py. Do not edit by hand.",
        "",
    ]
    for name in sorted(schemas):
        lines.append(f"export type {_type_name(name)} = {_schema_to_ts(schemas[name], schemas)};")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    app = create_app()
    openapi = app.openapi()

    OPENAPI_PATH.parent.mkdir(parents=True, exist_ok=True)
    TYPES_PATH.parent.mkdir(parents=True, exist_ok=True)
    OPENAPI_PATH.write_text(json.dumps(openapi, indent=2, sort_keys=True) + "\n")
    TYPES_PATH.write_text(_render_types(openapi))
    print(f"openapi={OPENAPI_PATH.relative_to(ROOT)}")
    print(f"types={TYPES_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
